### ISSUE TITLE
Search Cards [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1149]
**MapStories & StoryLayers Cards**
- [x] Generate thumbnails for StoryLayers and MapStories. If no thumbnails available, assign a default image. 
- [X] Display star rating properly.
- [x] Link "Read more." text to the storylayer/mapstory info page.
- [x] Wire up the favorites functionality to the Favorite button....or just remove button...OR just say "play" and have it go to viewer page just like clicking thumbnail
- [x] Display the author/storyteller. Required.
- [x] Display the topic (category) of the content. If there's no category assigned to the content, display "Uncategorized".
- [x] Hide private contents from public.
- [x] _For MapStory cards_: Play button should launch the full-screen MapStory playback.
- [x] _For StoryLayers cards_: Edit button should launch the MapLoom interface preloaded with that layer. 
- [x] _For StoryLayers cards_: Display the number of edits properly.
- [x] Remove "Share"

**StoryTellers Cards**
- [x] Display users avatars.
- [x] If location and company info are not specified, hide these lines.
- [x] Resize the View Profile and Message buttons.
- [x] Link View Profile button properly.
- [x] Message button should link to the Create Message page. "To:" field  should be preloaded with the user's name.

**Comment by travislbrundage** [comment]
"Generate thumbnails for StoryLayers and MapStories. If no thumbnails available, assign a default image."
Seems to have odd behaviour right now... code is there... it sometime works/works after a period of delay... my only possible inclination now could be elasticsearch? The thumbnail does appear to be generated correctly and has a link you can reach it at, it's just not immediately loaded in the search page, although it appears in the api it queries correctly.

"Wire up the favorites functionality to the Favorite button."
Putting this to the back of the list for now due to difficulties with the favorites app.

(JM - fine)

"Hide private contents from public."
Where are contents set to private? From what I can tell, I can only see the option to make something private in the layer upload. Is there any other place to set content to be private?
If content is set to be private, I assume only the user who created it gets to see/modify it?

(JM - on production, the public/private settings are part of the mapstory metadata, so when metadata is able to be edited by the owner, then the user can edit public/private settings too. We don't have this on Beta. My suggestion would be to add the option to set viewer settings underneath the layer next to the "message" icon - (which also needs to work...). It will be a drop-down just like in Production site where I can set my layer or mapstory as "private" or "public")

"For StoryLayers cards: Display the number of edits properly."
It's a bit complicated to extract the number of edits alone from the geogig edits app. The issue is because the search page is already bound to a different angular controller. A service would need to be created to inject the geogig functionality. Not something I can't do, just going to take a bit of time for me to get to. Pushing to the back of the list as well for now unless it's high priority.

(JM - That's fine. Instead of edits we could just use # of views exact same as mapstory cards)

"Display users avatars."
This should already be fixed, but something is going wrong with elasticsearch.

**Comment by travislbrundage** [comment]
"Message button should link to the Create Message page. "To:" field should be preloaded with the user's name."

Bare minimum is done, but To: field is currently not populated with the users name. Will circle back on this one to implement that as well as a text field with autocomplete rather than an endless dropdown menu.

**Comment by jonpmarino** [comment]
NIce. sounds good

**Comment by travislbrundage** [comment]
"Wire up the favorites functionality to the Favorite button....or just remove button...OR just say "play" and have it go to viewer page just like clicking thumbnail"
For now, just removed the favorite button on search. Will come back and implement it later. Favoriting works fine on the view page for MapStory and StoryLayers.

"For StoryLayers cards: Display the number of edits properly."
Temporarily just made to be number of views.
