### ISSUE TITLE
Content Info Pages [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1150]
**MapStory and StoryLayer Info Pages**
- [x] Add "Add tags" functionality, use a modal interface.
- [x] Enable flagging of contents, use a modal interface. (Talk to Jon about this)
- [x] Display Related contents properly. I sometimes see things with curly brackets.
- [x] Implement Star ratings (See attached images).
- [x] Add the word "MapStory" or "StoryLayer" above the title. (See attached image)
- [x] Titles should **not** be truncated.
- [ ] Add drop-down option for user to set their layer or mapstory as "public" or "private"...next to "message" button under the viewer square
- [X] Make sure user can update metadata on layers that belong to them

**MapStory Info Page**
- [x] _Play Fullscreen_ option links to a page with geonode header. Fix that.

**StoryLayer Info Page**
- [x] Show edit statistics in the _Edits_ tab.
- [x] Information under the _Metadata_ tab should be editable if the user is viewing his own storylayer.
- [x] Add Time Information in the StoryLayer metadata. We should be able to display the time range of the storylayer and display it on a human-readable format.

<img width="538" alt="screen shot 2015-08-07 at 10 32 26 am" src="https://cloud.githubusercontent.com/assets/4611843/9138214/6bb63436-3cf0-11e5-8c46-7737b554b6ce.png">

<img width="565" alt="screen shot 2015-08-07 at 10 29 21 am" src="https://cloud.githubusercontent.com/assets/4611843/9138215/6bb93744-3cf0-11e5-84d1-fee1f9bbc0a7.png">

Stars graphics:
![blank_star](https://cloud.githubusercontent.com/assets/4611843/9141753/f1f069e6-3d08-11e5-8cf0-40371a3040a5.png)
![full_star](https://cloud.githubusercontent.com/assets/4611843/9141754/f1f16eae-3d08-11e5-8fbf-565520cbfd6c.png)
![half_star](https://cloud.githubusercontent.com/assets/4611843/9141752/f1ec3b32-3d08-11e5-9e7e-adb6d0256a1d.png)

**Comment by travislbrundage** [comment]
"Titles should not be truncated." - are you seeing titles truncated on these pages? I have nothing set to truncate it in the code.

"Play Fullscreen option links to a page with geonode header. Fix that." Do you mean just fix the header?

**Comment by reynalddizon** [comment]
@travislbrundage 

"Titles should not be truncated." - are you seeing titles truncated on these pages? I have nothing set to truncate it in the code.
-Here's an example: http://mapstory.beta.boundlessgeo.com/layers/geonode%3ABirth_Place_Notable_Civil_Rights_Leaders

"Play Fullscreen option links to a page with geonode header. Fix that." Do you mean just fix the header?
-Yeah, just the header.

**Comment by travislbrundage** [comment]
The case you link is complicated because the title is all one string with no spaces (underscore is not a space). I think that wouldn't happen otherwise. I'm not sure off the top of my head how to fix that, but what would you want to happen in this case?

**Comment by travislbrundage** [comment]
"Add Time Information in the StoryLayer metadata. We should be able to display the time range of the storylayer and display it on a human-readable format."

Could you perhaps give a quick example of what this should look like?

**Comment by reynalddizon** [comment]
<img width="509" alt="screen shot 2015-08-10 at 8 02 11 pm" src="https://cloud.githubusercontent.com/assets/4611843/9187105/c185f16a-3f9a-11e5-867a-34e8894d913a.png">

**Comment by reynalddizon** [comment]
The source of information for Time Range should come from the data layer itself, getting the earliest and the latest timestamps. Let me know if thats technically possible, if not, we might just resort to manual entry.

**Comment by travislbrundage** [comment]
Okay, great, thank you for the clarifications! Not a problem at all, I was able to add that quickly just now.

So what if there is no temporal data? Just skip that row altogether?

**Comment by reynalddizon** [comment]
With this version of mapstory, we're hoping to "force" all users to put time information upon upload, but just in case, just display "No time information".

**Comment by travislbrundage** [comment]
Cool, that makes sense. Thanks.

**Comment by travislbrundage** [comment]
"Add drop-down option for user to set their layer or mapstory as "public" or "private"...next to "message" button under the viewer square"
Currently this exists in the Meta data tab.

**Comment by travislbrundage** [comment]
I don't think there is anything that actually tracks the number of times a layer/map has been rated. It only updates the average rating. It isn't impossible to add, but I'm not sure how quickly I could implement that.

**Comment by reynalddizon** [comment]
@travislbrundage the number of times the layer has been rated is not very essential. we can drop that. just make sure to display "Average rating" next to the stars.
