### ISSUE TITLE
Composer [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1152]
**General**
- [ ] add StoryStyles button under StoryLayers. Remove StoryStyles from header

**MapStory Metadata**
- [ ] Users should be able to choose a Topic from a dropdown list.
- [ ] Users should be able to add tags for the MapStory.
- [ ] Users should be able to "tag" other users as "Contributors". These users will also show it on MapStory Viewer page in a tab next to "Related".

**StoryLayers**
- [ ] Edit Attrib: Have this open up new window with maploom editor
- [ ] Edit Metadata: Have "Edit Metadata" open up StoryLayer viewer page in new browser window.
  ![Uploading Screen Shot 2015-08-07 at 3.12.24 PM.png…]()
- [x] Change edit style to Time Info

**StoryPreview**
- [ ] Set "Status of layer" to 1. only I can view (private) 2. Share publically
- [x] Make StoryPreview an actual preview of how story will look in Explore.
- [X] Make sure storypins can be previewed
