### ISSUE TITLE
Explore Page [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1153]
**Search Filters**
- [ ] Make sure the _What's Hot_ items are working properly.
- [x] What Filter: Filter the search results based on topics.
- [x] Where Filter: Make sure the map search is working
- [ ] When Filter: Make sure this filter is working
- [ ] Activate StoryTellers search filters...for Interests and Location. Should pull from Profile data.

**Comment by travislbrundage** [comment]
Just a personal note, this was all working before, so I assume this just has to be translated to work with elastic search.

**Comment by travislbrundage** [comment]
"When Filter: Make sure this filter is working" Filter itself works, just the calendar app that pops up doesn't work correctly.

**Comment by travislbrundage** [comment]
"Where Filter: Make sure the map search is working" The map itself is working.

Both the regions and keywords queries are having the same issue. They used to work, but now they aren't working because the query is holding them as an array. This used to work, but for some reason it doesn't seem to any longer. It held them as an array so that it can have more than one (so, you could query if a region is in Africa, America, or Europe at the same time). I'm not sure what the proper approach is to doing so now.

**Comment by jonpmarino** [comment]
Ok. If it only holds one at a time that's fine. Also if where is only with map now that's fine for now too

**Comment by travislbrundage** [comment]
It turns out I was wrong, it isn't the array causing the issue. I don't currently understand why it isn't working as I expect. It was working previously, now it isn't.

The map extent however is working fine.

**Comment by travislbrundage** [comment]
What's Hot items have been removed considering they are all broken.

**Comment by travislbrundage** [comment]
"When Filter: Make sure this filter is working"
I've temporarily removed the broken datepicker. Will add it back later when it's working properly.
