### ISSUE TITLE
Community Pages [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1154]
**Organization Pages**
- [x] Update the URL path. It should be like: _mapstory.org/organization-name_

**Initiative Pages**
- [x] Update the URL path. It should be like: _mapstory.org/initiative/initiative-name_
- [x] _Join_ should be replaced with text that says "Help lead this initiative! Send a message to one of the current Initiative Leads"
- [x] Remove "share this page"
- [x] Align the MapStories and StoryLayers properly. Currently, it looks like this: 
  <img width="1280" alt="screen shot 2015-08-10 at 10 41 32 am" src="https://cloud.githubusercontent.com/assets/4611843/9174189/617e7736-3f4c-11e5-9217-6033b35311f8.png">
- [x] Selecting layers in django and holding Control to select multiple layers selects everything in between. Need to have it so it only selects what is clicked.

**Comment by travislbrundage** [comment]
"Update the URL path. It should be like: mapstory.org/organization-name"
Having strange problems with this one again. Despite seemingly creating the regex correctly logically in my head, it doesn't work and breaks the site...

**Comment by travislbrundage** [comment]
"Update the URL path. It should be like: mapstory.org/organization-name"
As discussed in this morning's email thread, I will be changing it to mapstory.org/channels/organization-name.
