### ISSUE TITLE
Guest User Access [ToDo list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1155]
**Guests who are trying to access the following features should be prompted with the log-in/sign-up page:**
- [x] Upload link on the homepage. 
- [x] Composer links on the navbar and homepage link

**Action buttons in the search results card should be grayed out if the desired action requires signing in:**
- [ ] For _StoryLayer_ cards, compose, edit and favorite should be grayed out/disabled.
- [ ] For _MapStory_ cards, favorite should be grayed out/disabled.
- [ ] _For *StoryLayer_ cards, message should be grayed out/disabled.

**For StoryLayer info page, the following actions should be directed to the log-in/sign-up page:**
- [x] Composer mapstory
- [ ] Edit
- [ ] Favorite
- [ ] Flag

**For MapStory info page, the following actions should be directed to the log-in/sign-up page:**
- [ ] Favorite
- [ ] Flag
