### ISSUE TITLE
Profile [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1156]
- [X] Delete button takes you to a GeoNode stock page. Should keep you in MapStory>Profile
- [X] Make sure we've migrated over the user profile data that shows Education and Skills. Should go on Profile underneath a tab for "About (username)"
- [X] Typo in Volunteer Technical Community
- [x] Pull from GeoNode form ("edit profile") city, state (location) and Profile (about), and keywords (interests)

![about](https://cloud.githubusercontent.com/assets/2573761/9639230/0d52bd72-5179-11e5-89d0-468674cb6684.jpg)

**E-mail notifications**

**Comment by travislbrundage** [comment]
"Add an edit button."
What does this mean for a MapStory?

"Add an option to enable users to delete their profile."
Profiles cannot be deleted, which makes sense in geonode, because the data is all interconnected. A user can choose to deactivate their profile, however, their data will remain on the web site.

Technically I did find a way around this, but I feel uneasy using it. It seems like geonode is designed for you to -not- do this. However, you can go in the django admin panel and choose to delete a user. It won't succeed in deleting the user, but it does seem to remove all their StoryLayers/MapStories. My concern is that it might be leaving a lot of junk behind as well. So, although it may be possible, I personally do not think it is a good idea.

I think the best approach is simply to inform users that if they want all data associated with their account removed, they must manually remove it all themselves. They can then deactivate their account if they choose, but unfortunately, it seems like that doesn't do very much by default. All it does is prevent them from logging in again - their user information and account is actually all still there. The only thing I can think of is I can have it so that deactivated accounts do not show up on search, and so their profile information shows an error page if the account is deactivated.

"Add a check box for "Join the Volunteer Technical Community" to indicate that the user is part of that."
I'm sorry, I don't know what this means.

**Comment by jonpmarino** [comment]
I think edit button. For Mapstory was to launch it in composer in case the user wants to make changes to their Mapstory. But I'm not worried about this.

Fine on deactivate and manually remove content.

VTC can be accomplished with the interests field like we discussed. No need for something rlse
