### ISSUE TITLE
MapLoom Interface [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1157]
- [ ] Users should be able to MERGE/APPEND datasets from upload to a Maploom repo
- [ ] Users should be able to see their editing-enabled StoryLayers on MapLoom (with geometries and timeline displayed correctly.)
- [ ] Users should be able to add features on the map and consequently update the database.
- [ ] Users should be able to click on features and see the feature info.
- [ ] Users should be able to delete an existing feature.
- [ ] Users should be able to access the table and see and navigate thru all the information. Users should be able to close the table as well.
- [ ] Users should be able to change the basemap.
- [ ] Add a link/button to enable the users to compose a mapstory using the edited layer
  <img width="1280" alt="save" src="https://cloud.githubusercontent.com/assets/4611843/9179395/3aeffb76-3f6a-11e5-930b-9d5cb919df87.png">
- [ ] In Table View, editing attributes is okay, but cannot sort a column, which makes things very hard when there are more than a few pages.
- [ ] Would eventually be very helpful to not have pagination. I know that there is an application online that does allow scrolling very large datasets, where it dynamically updates. In the meantime, perhaps would be good to be able to type page number and jump to page. 
- [ ] Cannot add cumulative layers...or do cumulative playback -Needed to refresh screen to see features we added rather than having them appear right away 
- [ ] Got the following error when hitting "zoom to data" button: "The following script error has occurred: "TypeError: json.BoundingBox is undefined". It is recommended that you reload the web page to resolve any potential complications."
