### ISSUE TITLE
Uploader [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1158]
- [ ]  **Time format**: Users should be able to upload files no matter what the time format is, as long as it meets the minimum requirements for time attributes.
- [ ] Need a way for admin on the back end to assign pre-existing StoryLayers in mapstory into a geogig repo so they can be edited (or some solution)
- [ ] Merge datasets...build workflow atop the geogit repository merge function. User should be able to upload a layer, flag it for versioning and synch it with MapStory layers already in that are flagged for editing. Then have a merge workflow from rogue. 
- [ ] Make sure uploaded layers with edits enabled be editable in MapLoom.
- [ ] **Warper**; make sure we prompt user if they are seeking to upload a historic map that they can go to Warper first and then come back and upload the geotiff in mapstory. This can be accomplished just with text.
- [ ] **Layout**: Adopt the new layout (See mockup. website/upload.html)
- [ ] Need to make sure user can "set to private" or "make public"
