### ISSUE TITLE
Homepage [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1159]
- [x] When we link to the Get Started sections from Home links (students, teachers, etc) the jump link is a bit off
- [x] Link "MapStory help center" to help.mapstory.org
- [ ] Need a mobile behavior that maintains header. Perhaps looks like this:
  ![45678](https://cloud.githubusercontent.com/assets/2573761/8287493/476659a2-18de-11e5-9c56-872cda329897.jpg)
- [ ] Need to adjust mobile view for home page so that it is coherent for user
- [x] Remove dead link on "Community Initiatives" header. It is enough to link to the initiative icons themselves.

**Comment by travislbrundage** [comment]
As discussed last week, I had some work done towards making the site more mobile friendly, but it would be a stretch for me to get in by Friday along with everything else. Pushing it to the bottom of my list unless otherwise specified.

**Comment by jonpmarino** [comment]
@travislbrundage sounds good. We will knock out other priorities first. If we get there, we can make a run at the highest level mobile wins.

**Comment by travislbrundage** [comment]
The dead link on "Community Initiatives" had come from an overflow from the news items. It turns out the reason was quite simple: the News Items in the django admin were entered incorrectly. The last one happened to be missing its closing tag, causing the link to spill over.

**Comment by travislbrundage** [comment]
"When we link to the Get Started sections from Home links (students, teachers, etc) the jump link is a bit off"
Fixed, but kind of in a hack way. Added this line:

```
window.onload = setTimeout(function() {window.scrollBy(0, -50);},100);
```

So basically whenever you navigate to this page, it will scroll up a bit to offset the way the header pushes the view down. It needs to wait a bit to execute because of Chrome which will otherwise execute the Javascript before the page entirely loads, so arbitrarily set it to wait 1/10th of a second. This seems to get it most of the time, although I've had it happen once that it still executed too early. The `onload` part should _already_ be waiting for the page to fully load, so it makes no sense that I need a timeout as well, but it's only in Chrome. The browser probably has some strange optimizations causing the bug I guess.
