### ISSUE TITLE
Composer: Styling StoryLayers [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1160]
Users should be able to style their StoryLayers using the following Styles:
- [x] Simple (for Points, Lines and Polygons)
- [ ] Choropleth (for Points, Lines and Polygons)
- [x] Unique Values (for Points, Lines and Polygons)

-increase from 9 to double digits.
- [ ] Graduated (for Points and Lines)
- [ ] Icons commons needs to enable svg upload - tabled until next round

**Comment by jonpmarino** [comment]
Its possible Unique is already implemented in StoryTools but is not exposed yet.
