### ISSUE TITLE
Composer: StoryPins [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1161]
Users should be able to add StoryPins to their MapStories.
- [x] Implement the StoryPin editor design
- [ ] Enable StoryPins bulk upload (pursue easiest implementation possible....upload + example spreadsheet) (tabled)
- [ ] Users should have the ability to add (hosted) media elements (photos, videos, links and sound files). There should be supporting language so that user knows how to do this
- [x] StoryPins configuration persistence (StoryPins should be able to display the changes made after saving the MapStory for the first time) (covered by previous issue)
- [ ] Should be able to change the location of a StoryPin after it is placed

**Comment by reynalddizon** [comment]
<img width="1280" alt="screen shot 2015-09-02 at 10 04 10 am" src="https://cloud.githubusercontent.com/assets/4611843/9633292/0ec82f76-515a-11e5-8ad2-1b1a5471c8c6.png">

Bug: Saving story pins sometimes doesn't work. See screen cap, when i clicked the Save button, nothing happens. It seems like the pin is on the map but doesn't register in the timeline.
