### ISSUE TITLE
Composer: StoryBoxes [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1164]
- [ ] Adopt the accordion layout for story boxing. (later for Travis)
- [ ] When creating StoryBoxes, we should keep the whole length of the StoryLayer visible for the user. Right now, if we create a StoryBox it starts to make parts of the layer disappear. The user doesn't know what is there to continue creating his/her story.
- [ ] Use the main basemap to set the geographic bounds of the storybox. Having two maps could be confusing to users.

<img width="1280" alt="storybox" src="https://cloud.githubusercontent.com/assets/4611843/9255951/9c26ad5c-41ba-11e5-90fa-4be35e211ce9.png">

**StoryBox Settings Persistence**

The following settings should persist when setting up storyboxes.
- [ ] Time Frame
- [ ] Geographic bounds
- [ ] Playback rates
- [ ] Included Layers

**Others**
- [x] MapStories with no storyboxes set should be assigned a with default storybox depending on the time extent of the storylayers included and it should be refflected on the timeline on playback.Currently it looks like this: (saved mapstory, no storyboxes set, 1 storylayer, no pins)
  <img width="1280" alt="screen shot 2015-08-25 at 9 41 01 am" src="https://cloud.githubusercontent.com/assets/4611843/9468034/6d857ba2-4b0d-11e5-8b08-d53414b9cb24.png">
- [x] Timeline consistency: The timeline seems to get messed up when deleting storyboxes.

<img width="1280" alt="timeline" src="https://cloud.githubusercontent.com/assets/4611843/9276578/e24046a0-4272-11e5-8c78-10e78d848b6c.png">
- [x] Add "Days" in playback options.

**Comment by davisc** [comment]
I like it.

**Comment by jonpmarino** [comment]
Me too. Rey followed your model, @davisc so shouldn't be new tech, just new skin. One thought - Can we do more than simple text in the abstract? If people want to link to data or an image that they want in there?
