### ISSUE TITLE
Viewer and Playback [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1165]
-old mapstories need to play in full screen. quick fix seems to have "play full screen" go to same place as X link
- [ ] Looped animation button doesn't work
- [ ] Still need full screen/small screen button
- [ ] StoryLayers should be able to linked to in the StoryLayer button
- [ ] Legend should have a truncate so that it doesn't extend longer than the viewer...becomes scrollable
- [ ] The user should be able to simplify the date format in playback
- [ ] Tags on the viewer page should be interactive. Clicking one should take you to Explore>tag filter
- [X] Flag button brings up 2 sets of the flag options
