### ISSUE TITLE
Django admin fixes [To-Do List]

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1166]
- [x] Need to be able to successfully delete layers and mapstories without errors
- [x] Need to be able to assign layers and stories to topics and Featured without errors
- [x] Set powers of Content-Mod group member...to be able, on front end of mapstory.org, to be able to edit metadata and change viewer status (private, public)

**Comment by jonpmarino** [comment]
I am still getting a reoccurring error when I try to assign Topics to mapstories or I try to set them as featured. It asks me to "please enter a URL" inside the circle below

![topics error](https://cloud.githubusercontent.com/assets/2573761/9632924/e3e3e1f8-5157-11e5-915f-f979bd3029ae.jpg)

**Comment by travislbrundage** [comment]
So it seems the conclusion for now is that the problem lies in the data migration. Oddly, those URLs are working although they are not correctly passing django's validation. Making them go to https://mapstory.org/[ows_url] seems to fix the issue, although do we want to point to mapstory.org?

There are also many layers/maps that have issues with CSW fields and a few others. It always seems to be the same few fields.

**Comment by travislbrundage** [comment]
Everything in here should be done, with the exception of data migration issues. Those are an unrelated issue. The django admin should be working fine.
