### ISSUE TITLE
Miscellaneous links and cleanup [To-Do List]

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1169]
- [x] In metadata page of uploader, change "update" button to "Save as Draft". Add additional language next to button: "Once you hit save, your StoryLayer will appear in your Profile as a private draft. To make it Public for everyone to see and use, you can switch the viewing status in the metadata tab of the StoryLayer"
- [x] remove lorem ipsum in Uploader and replace with "Having problems? Click here (http://wiki.mapstory.org/wiki/MapStory_Uploader) for more resources to help you with Upload. Or visit help.mapstory.org and post your question for the community"
- [x] On Sign Up, make sure "Signing Up as an Organization?" goes to the Organization Pages jump at http://mapstory.beta.boundlessgeo.com/getinvolved.
- [x] In user drop-down, make "Help" link go to help.mapstory.org not to the GeoNode page it currently goes to. (see screenshot)
  ![helpshow](https://cloud.githubusercontent.com/assets/2573761/9639425/fafb017e-5179-11e5-88d3-971d2d539d59.jpg)
- [x] On Sign Up, make sure "forget password?" actually sends you to a place to change your passsword
- [X] make sure all links open up a new browser page rather than taking you away from mapstory.org
- [x] Facebook and Google log-in should either work or be taken out
- [x] Add link in Footer for | Merchandise. Make link to http://mapstory.myshopify.com/
- [x] Add help.mapstory.org to footer next to wiki.mapstory.org. Also be nice to have an (i) icon to the right of the Gihub/Twitter/FB icons underneath the donate now button
- [x] At  http://mapstory.beta.boundlessgeo.com/donate#, "Sponsor an Organization Page" should link to http://mapstory.beta.boundlessgeo.com/getinvolved (jump to Organization PAge). Also "Make a Donation" should link to our paypal page - https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=XaafvZ7H3UFGdzyQaK8qY9oGXEQWNiswU2riVumtsc2HmO7OEvTQoFRUui8&dispatch=5885d80a13c0db1f8e263663d3faee8d5c97cbf3d75cb63effe5661cdf3adb6d
- [x] In Footer, Reference to "Terms of Service" and "Privacy Policy" should link to http://wiki.mapstory.org/wiki/Terms_of_Service

**Comment by travislbrundage** [comment]
"make sure all links open up a new browser page rather than taking you away from mapstory.org" What is this referring to? Any external links? What links are not behaving as they should? Is this just all the links in the footer?

"Also be nice to have an (i) icon to the right of the Gihub/Twitter/FB icons underneath the donate now button" what's an (i) icon? Can you please clarify what is being looked for here?

**Comment by jonpmarino** [comment]
@travislbrundage great questions. On #1 we meant mostly in composer...if we are clicking to thinks (for example, when we do "edit metadata" and it takes you to the viewer page, that you don't get taken out of your composer project, but that it opens up a new browser window with the content. So you don't lose what you're working on. Easy to explain in hangout if need.

On #2 the point was to make sure we have a link to help.mapstory.org in the footer, so user can always access it. That could be accomplished by adding help.mapstory.org as a link in the very bottom next to | wiki.mapstory.org or some kind of "help" indicating icon next to the social media bottons. This would link to our help.mapstory.org askbot instance

**Comment by travislbrundage** [comment]
Gotcha, thanks for the clarifications! I understand them both now. Makes sense.

**Comment by travislbrundage** [comment]
So I went through composer looking for links that took you away from the application, but I couldn't find anything? Maybe we could do a hangout and discuss what specifically you're referring to?

**Comment by jonpmarino** [comment]
@travislbrundage mostly when "edit style", "edit attribute" and "edit metadata" tabs are activated they should open up new browser windows rather than taking you out of your composer project. But I think @davisc is going to implement.

![78900](https://cloud.githubusercontent.com/assets/2573761/9580217/23504e32-4fc6-11e5-878f-f1ebaf88f55a.jpg)
