### ISSUE TITLE
Profile finishing touches [To-Do List]

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1170]
- [ ] Make sure data from education and blurb on MapStory.org is ported over to beta profile
- [ ] Make sure user can set email notification settings of whether they want to be notified when/if another user comments on, rates or uses one of their StoryLayers...same implementation as production. (editing would be good too, but probably too much.
  ![909090](https://cloud.githubusercontent.com/assets/2573761/9361828/51cf9e20-466b-11e5-9a13-50d33a363160.jpg)
- [ ] Make sure to add a small check box for "Show me as a member of the Volunteer Technical Community". If checked, on the user's profile it'll just indicate that user is "Volunteer Technical Community Member". That's all.
- [ ] Reach goal - would be nice to have the same functionality we have on prod that lets a user send an email "invite" to someone else, inviting them to create a mapstory.org...enabling viral spread. Best implementation would be to have a field on "create profile" that integrates with inviting Facebook friends or email contacts.
