### ISSUE TITLE
Managing MapStories [To-Do list]

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1173]
- [ ] Enable editing of mapstories after publishing them. Currently, the only way to do this is by staying in the composer after saving your mapstory. Once you close the composer there's no way that you can get back to editing that mapstory. (clarence)
- [ ] Changes made after re-editing them should persist. (clarence)
- [ ] Users should have the ability to delete a mapstory in their profile page. After deleting, user should return to profile page, not to this random GeoNode page - 
  ![5656](https://cloud.githubusercontent.com/assets/2573761/9721981/2b101da2-5573-11e5-9ee1-b51c732f4a58.jpg)
  (travis)
