### ISSUE TITLE
Summary statement on this week

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1478]
There's tons of issues in 4-till geont. This is a summary issue as a one-stop-shop for the big-picture end-state were trying to get to. Primary goal for the week is to close the full loop on composer to create exemplar mapstories. All issues mentioned are tagged with "MapStories Last Mile".

**Inside composer:**
- [x] StoryBox persistence - #1465  (John)
- [x] Time control breaking - #1282 (Clarence)
  -Returning to save - #1315 
- [X] Layer doesn't load in composer in chapter 1 right away (Jon)- #1456 

**getting into/out of composer / editor (Jeremiah):**
- [x] Properties modal - #1449
- [X] header - #1428 
- [X] back to StoryLayers button in edit-only - #1481 

**Playing back published mapstories**
-css of sidebar and linking - #1359 (Mila)
-getting new functionality (storypins, storyboxes, infoboxes) on playback #1470 (clarence)

**Finding published mapstories to playback (Travis)**
- [X] viewer page #1473 
- [ ] card #1437 
- [ ] filter #1444 

**And finishing up Append from before...**
-Ariel (set of issues)
