### ISSUE TITLE
meta project creation

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#969]
- [ ] remove/move existing code from mapstory/mapstory
- [x] add build + submodules
- [x] build script
- [ ] deploy war script
- [x] verify on dev
